project:
  type: website
  render:
    - "*.qmd"
    - "!notes/"

execute:
  freeze: auto
  #echo: false
  warning: false
  message: false

website:
  title: ""
  navbar:
    title: ""
    left:
      - href: "/"
        text: Calendar
        icon: calendar-check
      - href: sidebar:archive
        # text: Archive
        icon: archive
    right:
      - href: https://github.com/nshlab/labmeeting
        icon: github
      - href: https://nimahejazi.org
        icon: house
  sidebar:
    - id: archive
      # icon: archive
      title: "Archive"
      contents:
        - auto: archive
  search: true
  open-graph: true
  reader-mode: false
  page-footer:
    left: "&copy; 2024--2025 [Nima Hejazi](https://nimahejazi.org)"
    center: "last updated: {{< meta date >}}"
    right: "built with [quarto](https://quarto.org)"
  site-url: "https://lab.nimahejazi.org/labmeeting/"
  repo-url: "https://github.com/nshlab/labmeeting/"
  repo-branch: main
  repo-actions: [edit, issue]

format:
  html:
    date: last-modified
    date-format: "DD MMMM YYYY"
    theme: [simplex, styles.scss]
    include-in-header: mathjax.html
    css: hide_date.css
    smooth-scroll: true
    # ToC options
    toc: false
    toc-depth: 2
    toc-title: Contents
    # citations/references
    reference-location: margin
    citation-location: document
    citations-hover: true
    footnotes-hover: true
    # figure options
    fig-width: 8
    fig-asp: 0.618
    # code block options
    code-copy: true
    code-link: true
    code-fold: true
    code-tools: false
    code-line-numbers: true
    code-block-bg: dark
    highlight-style: ayu-mirage

bibliography: refs.bib
