---
title: "2026 Fall"
section-divs: false
sidebar: false
---

## Meeting Schedule

| Date              | Room      | Topic | Reading | Presenter |
| ----------------- | --------- | ---------------------- | --------------- | --------- |
| 8^th^ September | 2-426 | kickoff meeting | | NSH |
| 15^th^ September | 2-426 | foundations of targeted maximum likelihood | @vdl2006targeted; and Appx. A.1--A.3 of @vdl2011targeted | |
| 22^nd^ September | **2-401** | research connections | | |
| 29^th^ September | 2-426 | foundations of targeted maximum likelihood | @gruber2010bounded; and Appx. A.4--A.6 of @vdl2011targeted | |
| 6^th^ October | 2-426 | research connections | | |
| 13^th^ October | 2-426 | double machine learning | @chernozhukov2018double | |
| 20^th^ October | 2-426 | research connections | | |
| 27^th^ October | 2-426 | orthogonal statistical learning | @foster2023orthogonal | |
| 3^rd^ November | 2-426 | research connections | | |
| 10^th^ November | 2-426 | doubly robust inference | @benkeser2017doubly | |
| 17^th^ November | 2-426 | research connections | | |
| ~~24^th^ November~~ | ~~2-426~~ | [***canceled***---thanksgiving]{.underline} | | |
| 1^st^ December | 2-426 | research connections | | |
| 8^th^ December | 2-426 | Neyman orthogonality and pathwise differentiability | @chen2026equivalence | |
| 15^th^ December | 2-426 | Gaussian process limit of BART | @mccartan2026gaussian | SVB |

: Note: [We will meet ***weekly on Tuesdays, 2:00--4:00PM***, almost always in
2-426 (except for on 22^nd^ September).]{.underline}

Our theme this term is [*foundations of causal machine learning*]{.underline},
with a focus on contemporary frameworks, particularly targeted learning
[@vdl2006targeted; @gruber2010bounded; @vdl2011targeted] to construct
asymptotically linear estimators of pathwise differentiable statistical
parameters and double machine learning for Neyman orthogonal statistical
parameters [@chernozhukov2018double; @foster2023orthogonal]. To deepen our
perspective, we will consider topics that cut across these frameworks and
stretch into semi-parametric efficiency theory, including doubly robust
inference [@benkeser2017doubly], the relationship between pathwise
differentiability and Neyman orthognality [@chen2026equivalence], and advances
in the estimation of nuisance functions [@mccartan2026gaussian]. As with
[Spring 2026](archive/spring2026.qmd), meetings will alternate weekly between
chalk-talk presentations of the assigned readings and informal
research-connection talks intended to explore overlap between this theme and
areas of ongoing research in our group.

Time permitting, we may discuss additional topics---listed below---which may
replace readings in the above list (pending group discussion) or otherwise
serve as potential readings for Spring 2027.

- **Classics in semi-parametric theory**: @klaassen1987consistent,
  @robins1995semiparametric
- **Efficient inference in time-varying, longitudinal settings**:
  @diaz2021nonparametric, @luedtke2018sequential, @diaz2024causal,
  @diaz2026modified, @murphy2003optimal, @rotnitzky2017multiply
* **Frontier topics (function estimation, adaptive inference, and more)**:
  @westling2020causal, @kennedy2023towards, @chernozhukov2024conditional,
  @lan2024causal, @vanderlaan2025automatic, @luedtke2024onestep,
  @vanderlaan2026calibeating, @liu2017semiparametric, @liu2020nearly


## References

::: {#refs}
:::
