---
title: "2025 Spring"
section-divs: false
sidebar: false
---

## Meeting Schedule

| Date            | Topic                  | Reading          | Presenter   |
|-----------------|------------------------|------------------|-------------|
| 3^rd^ February  | Overview of M- and Z-estimation | Ch. 5 of @vdvaart1998asymptotic and Ch. 1-3 of @kosorok2008introduction. | NH |
| 18^th^ February (Tuesday) | Some empirical process theory | Ch. 7-9 of @vdvaart1998asymptotic and Ch. 5-6 of @kosorok2008introduction. | CT |
| 3^rd^ March     | More empirical process theory | Ch. 7-8 of @kosorok2008introduction and Ch. 18-19 of @vdvaart1998asymptotic. | SVB |
| 17^th^ March    | The functional delta method | Ch. 12-14 of @kosorok2008introduction and Ch. 20 of @vdvaart1998asymptotic. | CJ |
| 31^st^ March    | Efficient semiparametric inference | Ch. 16-17  and Sec. 18.1 of @kosorok2008introduction. | NSH |
| 14^th^ April (Tuesday)    | Efficient semiparametric inference | Sec. 18.2-18.3 of @kosorok2008introduction. | NSH |
| 5^th^ May    | Efficient semiparametric inference | Appx. A.1-A.5 of @vdl2011targeted. | NH |
| 19^th^ May    | Efficient semiparametric inference | Sec. 19.1-19.2, Ch. 20, and Sec. 21.1-21.2 of @kosorok2008introduction. | SVB |

: Our meetings will *usually* be held **on Mondays**, 3:30-5:00 PM, in HSPH 2-426.

## References

::: {#refs}
:::
